// <auto-generated />
using System;
using System.Collections.Generic;
using Cleanuparr.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cleanuparr.Persistence.Migrations.Data
{
    [DbContext(typeof(DataContext))]
    [Migration("20260620165140_AddUnlinkedTagFilters")]
    partial class AddUnlinkedTagFilters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Arr.ArrConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<short>("FailedImportMaxStrikes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed_import_max_strikes");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_arr_configs");

                    b.ToTable("arr_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Arr.ArrInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("api_key");

                    b.Property<Guid>("ArrConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("arr_config_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<float>("Version")
                        .HasColumnType("REAL")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_arr_instances");

                    b.HasIndex("ArrConfigId")
                        .HasDatabaseName("ix_arr_instances_arr_config_id");

                    b.ToTable("arr_instances", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.BlacklistSync.BlacklistSyncConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BlacklistPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("blacklist_path");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.HasKey("Id")
                        .HasName("pk_blacklist_sync_configs");

                    b.ToTable("blacklist_sync_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.DeadTorrentConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("categories");

                    b.Property<Guid>("DownloadClientConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("download_client_config_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<ushort>("MaxStrikes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_strikes");

                    b.Property<string>("TargetCategory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_category");

                    b.Property<bool>("UseTag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("use_tag");

                    b.HasKey("Id")
                        .HasName("pk_dead_torrent_configs");

                    b.HasIndex("DownloadClientConfigId")
                        .IsUnique()
                        .HasDatabaseName("ix_dead_torrent_configs_download_client_config_id");

                    b.ToTable("dead_torrent_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.DelugeSeedingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("categories");

                    b.Property<bool>("DeleteSourceFiles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delete_source_files");

                    b.Property<Guid>("DownloadClientConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("download_client_config_id");

                    b.Property<double>("MaxRatio")
                        .HasColumnType("REAL")
                        .HasColumnName("max_ratio");

                    b.Property<double>("MaxSeedTime")
                        .HasColumnType("REAL")
                        .HasColumnName("max_seed_time");

                    b.Property<double>("MinSeedTime")
                        .HasColumnType("REAL")
                        .HasColumnName("min_seed_time");

                    b.Property<int>("MinSeeders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_seeders");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("PrivacyType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("privacy_type");

                    b.Property<string>("TrackerPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tracker_patterns");

                    b.HasKey("Id")
                        .HasName("pk_deluge_seeding_rules");

                    b.HasIndex("DownloadClientConfigId")
                        .HasDatabaseName("ix_deluge_seeding_rules_download_client_config_id");

                    b.ToTable("deluge_seeding_rules", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.DownloadCleanerConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.PrimitiveCollection<string>("IgnoredDownloads")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ignored_downloads");

                    b.Property<bool>("UseAdvancedScheduling")
                        .HasColumnType("INTEGER")
                        .HasColumnName("use_advanced_scheduling");

                    b.HasKey("Id")
                        .HasName("pk_download_cleaner_configs");

                    b.ToTable("download_cleaner_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.OrphanedFilesConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("DownloadClientConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("download_client_config_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("ExcludePatterns")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("exclude_patterns");

                    b.Property<int>("MinFileAgeHours")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_file_age_hours");

                    b.Property<string>("OrphanedDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("orphaned_directory");

                    b.Property<int?>("PurgeAfterHours")
                        .HasColumnType("INTEGER")
                        .HasColumnName("purge_after_hours");

                    b.Property<string>("ScanDirectories")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scan_directories");

                    b.HasKey("Id")
                        .HasName("pk_orphaned_files_configs");

                    b.HasIndex("DownloadClientConfigId")
                        .IsUnique()
                        .HasDatabaseName("ix_orphaned_files_configs_download_client_config_id");

                    b.ToTable("orphaned_files_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.QBitSeedingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("categories");

                    b.Property<bool>("DeleteSourceFiles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delete_source_files");

                    b.Property<Guid>("DownloadClientConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("download_client_config_id");

                    b.Property<double>("MaxRatio")
                        .HasColumnType("REAL")
                        .HasColumnName("max_ratio");

                    b.Property<double>("MaxSeedTime")
                        .HasColumnType("REAL")
                        .HasColumnName("max_seed_time");

                    b.Property<double>("MinSeedTime")
                        .HasColumnType("REAL")
                        .HasColumnName("min_seed_time");

                    b.Property<int>("MinSeeders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_seeders");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("PrivacyType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("privacy_type");

                    b.Property<string>("TagsAll")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags_all");

                    b.Property<string>("TagsAny")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags_any");

                    b.Property<string>("TrackerPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tracker_patterns");

                    b.HasKey("Id")
                        .HasName("pk_q_bit_seeding_rules");

                    b.HasIndex("DownloadClientConfigId")
                        .HasDatabaseName("ix_q_bit_seeding_rules_download_client_config_id");

                    b.ToTable("q_bit_seeding_rules", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.RTorrentSeedingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("categories");

                    b.Property<bool>("DeleteSourceFiles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delete_source_files");

                    b.Property<Guid>("DownloadClientConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("download_client_config_id");

                    b.Property<double>("MaxRatio")
                        .HasColumnType("REAL")
                        .HasColumnName("max_ratio");

                    b.Property<double>("MaxSeedTime")
                        .HasColumnType("REAL")
                        .HasColumnName("max_seed_time");

                    b.Property<double>("MinSeedTime")
                        .HasColumnType("REAL")
                        .HasColumnName("min_seed_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("PrivacyType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("privacy_type");

                    b.Property<string>("TrackerPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tracker_patterns");

                    b.HasKey("Id")
                        .HasName("pk_r_torrent_seeding_rules");

                    b.HasIndex("DownloadClientConfigId")
                        .HasDatabaseName("ix_r_torrent_seeding_rules_download_client_config_id");

                    b.ToTable("r_torrent_seeding_rules", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.TransmissionSeedingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("categories");

                    b.Property<bool>("DeleteSourceFiles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delete_source_files");

                    b.Property<Guid>("DownloadClientConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("download_client_config_id");

                    b.Property<double>("MaxRatio")
                        .HasColumnType("REAL")
                        .HasColumnName("max_ratio");

                    b.Property<double>("MaxSeedTime")
                        .HasColumnType("REAL")
                        .HasColumnName("max_seed_time");

                    b.Property<double>("MinSeedTime")
                        .HasColumnType("REAL")
                        .HasColumnName("min_seed_time");

                    b.Property<int>("MinSeeders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_seeders");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("PrivacyType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("privacy_type");

                    b.Property<string>("TagsAll")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags_all");

                    b.Property<string>("TagsAny")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags_any");

                    b.Property<string>("TrackerPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tracker_patterns");

                    b.HasKey("Id")
                        .HasName("pk_transmission_seeding_rules");

                    b.HasIndex("DownloadClientConfigId")
                        .HasDatabaseName("ix_transmission_seeding_rules_download_client_config_id");

                    b.ToTable("transmission_seeding_rules", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.UTorrentSeedingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("categories");

                    b.Property<bool>("DeleteSourceFiles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delete_source_files");

                    b.Property<Guid>("DownloadClientConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("download_client_config_id");

                    b.Property<double>("MaxRatio")
                        .HasColumnType("REAL")
                        .HasColumnName("max_ratio");

                    b.Property<double>("MaxSeedTime")
                        .HasColumnType("REAL")
                        .HasColumnName("max_seed_time");

                    b.Property<double>("MinSeedTime")
                        .HasColumnType("REAL")
                        .HasColumnName("min_seed_time");

                    b.Property<int>("MinSeeders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_seeders");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("PrivacyType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("privacy_type");

                    b.Property<string>("TrackerPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tracker_patterns");

                    b.HasKey("Id")
                        .HasName("pk_u_torrent_seeding_rules");

                    b.HasIndex("DownloadClientConfigId")
                        .HasDatabaseName("ix_u_torrent_seeding_rules_download_client_config_id");

                    b.ToTable("u_torrent_seeding_rules", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.UnlinkedConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("categories");

                    b.Property<Guid>("DownloadClientConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("download_client_config_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.PrimitiveCollection<string>("IgnoredRootDirs")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ignored_root_dirs");

                    b.PrimitiveCollection<string>("TagsAll")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags_all");

                    b.PrimitiveCollection<string>("TagsAny")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags_any");

                    b.Property<string>("TargetCategory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_category");

                    b.Property<bool>("UseTag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("use_tag");

                    b.HasKey("Id")
                        .HasName("pk_unlinked_configs");

                    b.HasIndex("DownloadClientConfigId")
                        .IsUnique()
                        .HasDatabaseName("ix_unlinked_configs_download_client_config_id");

                    b.ToTable("unlinked_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadClientConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DownloadDirectorySource")
                        .HasColumnType("TEXT")
                        .HasColumnName("download_directory_source");

                    b.Property<string>("DownloadDirectoryTarget")
                        .HasColumnType("TEXT")
                        .HasColumnName("download_directory_target");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_url");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type_name");

                    b.Property<string>("UrlBase")
                        .HasColumnType("TEXT")
                        .HasColumnName("url_base");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_download_clients");

                    b.ToTable("download_clients", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.General.GeneralConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("DisplaySupportBanner")
                        .HasColumnType("INTEGER")
                        .HasColumnName("display_support_banner");

                    b.Property<bool>("DryRun")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dry_run");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("encryption_key");

                    b.Property<string>("HttpCertificateValidation")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("http_certificate_validation");

                    b.Property<ushort>("HttpMaxRetries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("http_max_retries");

                    b.Property<ushort>("HttpTimeout")
                        .HasColumnType("INTEGER")
                        .HasColumnName("http_timeout");

                    b.PrimitiveCollection<string>("IgnoredDownloads")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ignored_downloads");

                    b.Property<bool>("StatusCheckEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_check_enabled");

                    b.Property<ushort>("StrikeInactivityWindowHours")
                        .HasColumnType("INTEGER")
                        .HasColumnName("strike_inactivity_window_hours");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Auth", "Cleanuparr.Persistence.Models.Configuration.General.GeneralConfig.Auth#AuthConfig", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("DisableAuthForLocalAddresses")
                                .HasColumnType("INTEGER")
                                .HasColumnName("auth_disable_auth_for_local_addresses");

                            b1.Property<bool>("TrustForwardedHeaders")
                                .HasColumnType("INTEGER")
                                .HasColumnName("auth_trust_forwarded_headers");

                            b1.Property<string>("TrustedNetworks")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("auth_trusted_networks");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Log", "Cleanuparr.Persistence.Models.Configuration.General.GeneralConfig.Log#LoggingConfig", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("ArchiveEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("log_archive_enabled");

                            b1.Property<ushort>("ArchiveRetainedCount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("log_archive_retained_count");

                            b1.Property<ushort>("ArchiveTimeLimitHours")
                                .HasColumnType("INTEGER")
                                .HasColumnName("log_archive_time_limit_hours");

                            b1.Property<string>("Level")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("log_level");

                            b1.Property<ushort>("RetainedFileCount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("log_retained_file_count");

                            b1.Property<ushort>("RollingSizeMB")
                                .HasColumnType("INTEGER")
                                .HasColumnName("log_rolling_size_mb");

                            b1.Property<ushort>("TimeLimitHours")
                                .HasColumnType("INTEGER")
                                .HasColumnName("log_time_limit_hours");
                        });

                    b.HasKey("Id")
                        .HasName("pk_general_configs");

                    b.ToTable("general_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.MalwareBlocker.ContentBlockerConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("DeleteIfAnyFileBlocked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delete_if_any_file_blocked");

                    b.Property<bool>("DeletePrivate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delete_private");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<bool>("IgnorePrivate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ignore_private");

                    b.PrimitiveCollection<string>("IgnoredDownloads")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ignored_downloads");

                    b.Property<bool>("ProcessNoContentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("process_no_content_id");

                    b.Property<bool>("UseAdvancedScheduling")
                        .HasColumnType("INTEGER")
                        .HasColumnName("use_advanced_scheduling");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Lidarr", "Cleanuparr.Persistence.Models.Configuration.MalwareBlocker.ContentBlockerConfig.Lidarr#BlocklistSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("BlocklistPath")
                                .HasColumnType("TEXT")
                                .HasColumnName("lidarr_blocklist_path");

                            b1.Property<string>("BlocklistType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("lidarr_blocklist_type");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("lidarr_enabled");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Radarr", "Cleanuparr.Persistence.Models.Configuration.MalwareBlocker.ContentBlockerConfig.Radarr#BlocklistSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("BlocklistPath")
                                .HasColumnType("TEXT")
                                .HasColumnName("radarr_blocklist_path");

                            b1.Property<string>("BlocklistType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("radarr_blocklist_type");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("radarr_enabled");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Readarr", "Cleanuparr.Persistence.Models.Configuration.MalwareBlocker.ContentBlockerConfig.Readarr#BlocklistSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("BlocklistPath")
                                .HasColumnType("TEXT")
                                .HasColumnName("readarr_blocklist_path");

                            b1.Property<string>("BlocklistType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("readarr_blocklist_type");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("readarr_enabled");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Sonarr", "Cleanuparr.Persistence.Models.Configuration.MalwareBlocker.ContentBlockerConfig.Sonarr#BlocklistSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("BlocklistPath")
                                .HasColumnType("TEXT")
                                .HasColumnName("sonarr_blocklist_path");

                            b1.Property<string>("BlocklistType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("sonarr_blocklist_type");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("sonarr_enabled");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Whisparr", "Cleanuparr.Persistence.Models.Configuration.MalwareBlocker.ContentBlockerConfig.Whisparr#BlocklistSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("BlocklistPath")
                                .HasColumnType("TEXT")
                                .HasColumnName("whisparr_blocklist_path");

                            b1.Property<int>("BlocklistType")
                                .HasColumnType("INTEGER")
                                .HasColumnName("whisparr_blocklist_type");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("whisparr_enabled");
                        });

                    b.HasKey("Id")
                        .HasName("pk_content_blocker_configs");

                    b.ToTable("content_blocker_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.AppriseConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<Guid>("NotificationConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("notification_config_id");

                    b.Property<string>("ServiceUrls")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("service_urls");

                    b.Property<string>("Tags")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_apprise_configs");

                    b.HasIndex("NotificationConfigId")
                        .IsUnique()
                        .HasDatabaseName("ix_apprise_configs_notification_config_id");

                    b.ToTable("apprise_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.DiscordConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_url");

                    b.Property<Guid>("NotificationConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("notification_config_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id")
                        .HasName("pk_discord_configs");

                    b.HasIndex("NotificationConfigId")
                        .IsUnique()
                        .HasDatabaseName("ix_discord_configs_notification_config_id");

                    b.ToTable("discord_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.GotifyConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("application_token");

                    b.Property<Guid>("NotificationConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("notification_config_id");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("ServerUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("server_url");

                    b.HasKey("Id")
                        .HasName("pk_gotify_configs");

                    b.HasIndex("NotificationConfigId")
                        .IsUnique()
                        .HasDatabaseName("ix_gotify_configs_notification_config_id");

                    b.ToTable("gotify_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.NotifiarrConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("api_key");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_id");

                    b.Property<Guid>("NotificationConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("notification_config_id");

                    b.HasKey("Id")
                        .HasName("pk_notifiarr_configs");

                    b.HasIndex("NotificationConfigId")
                        .IsUnique()
                        .HasDatabaseName("ix_notifiarr_configs_notification_config_id");

                    b.ToTable("notifiarr_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.NotificationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<bool>("OnCategoryChanged")
                        .HasColumnType("INTEGER")
                        .HasColumnName("on_category_changed");

                    b.Property<bool>("OnDownloadCleaned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("on_download_cleaned");

                    b.Property<bool>("OnFailedImportStrike")
                        .HasColumnType("INTEGER")
                        .HasColumnName("on_failed_import_strike");

                    b.Property<bool>("OnQueueItemDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("on_queue_item_deleted");

                    b.Property<bool>("OnSearchItemGrabbed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("on_search_item_grabbed");

                    b.Property<bool>("OnSearchTriggered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("on_search_triggered");

                    b.Property<bool>("OnSlowStrike")
                        .HasColumnType("INTEGER")
                        .HasColumnName("on_slow_strike");

                    b.Property<bool>("OnStalledStrike")
                        .HasColumnType("INTEGER")
                        .HasColumnName("on_stalled_strike");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notification_configs");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_configs_name");

                    b.ToTable("notification_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.NtfyConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("access_token");

                    b.Property<string>("AuthenticationType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("authentication_type");

                    b.Property<Guid>("NotificationConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("notification_config_id");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("priority");

                    b.Property<string>("ServerUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("server_url");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.PrimitiveCollection<string>("Topics")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("topics");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_ntfy_configs");

                    b.HasIndex("NotificationConfigId")
                        .IsUnique()
                        .HasDatabaseName("ix_ntfy_configs_notification_config_id");

                    b.ToTable("ntfy_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.PushoverConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ApiToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("api_token");

                    b.Property<string>("Devices")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("devices");

                    b.Property<int?>("Expire")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expire");

                    b.Property<Guid>("NotificationConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("notification_config_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("priority");

                    b.Property<int?>("Retry")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry");

                    b.Property<string>("Sound")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("sound");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_key");

                    b.HasKey("Id")
                        .HasName("pk_pushover_configs");

                    b.HasIndex("NotificationConfigId")
                        .IsUnique()
                        .HasDatabaseName("ix_pushover_configs_notification_config_id");

                    b.ToTable("pushover_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.TelegramConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BotToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("bot_token");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("chat_id");

                    b.Property<Guid>("NotificationConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("notification_config_id");

                    b.Property<bool>("SendSilently")
                        .HasColumnType("INTEGER")
                        .HasColumnName("send_silently");

                    b.Property<string>("TopicId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("pk_telegram_configs");

                    b.HasIndex("NotificationConfigId")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_configs_notification_config_id");

                    b.ToTable("telegram_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.QueueCleaner.QueueCleanerConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cron_expression");

                    b.Property<ushort>("DownloadingMetadataMaxStrikes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("downloading_metadata_max_strikes");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.PrimitiveCollection<string>("IgnoredDownloads")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ignored_downloads");

                    b.Property<bool>("ProcessNoContentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("process_no_content_id");

                    b.Property<bool>("UseAdvancedScheduling")
                        .HasColumnType("INTEGER")
                        .HasColumnName("use_advanced_scheduling");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FailedImport", "Cleanuparr.Persistence.Models.Configuration.QueueCleaner.QueueCleanerConfig.FailedImport#FailedImportConfig", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("ChangeCategory")
                                .HasColumnType("INTEGER")
                                .HasColumnName("failed_import_change_category");

                            b1.Property<bool>("DeletePrivate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("failed_import_delete_private");

                            b1.Property<bool>("IgnorePrivate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("failed_import_ignore_private");

                            b1.Property<ushort>("MaxStrikes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("failed_import_max_strikes");

                            b1.Property<string>("PatternMode")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("failed_import_pattern_mode");

                            b1.PrimitiveCollection<string>("Patterns")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("failed_import_patterns");

                            b1.Property<bool>("SkipIfNotFoundInClient")
                                .HasColumnType("INTEGER")
                                .HasColumnName("failed_import_skip_if_not_found_in_client");
                        });

                    b.HasKey("Id")
                        .HasName("pk_queue_cleaner_configs");

                    b.ToTable("queue_cleaner_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.QueueCleaner.SlowRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("ChangeCategory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("change_category");

                    b.Property<bool>("DeletePrivateTorrentsFromClient")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delete_private_torrents_from_client");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("IgnoreAboveSize")
                        .HasColumnType("TEXT")
                        .HasColumnName("ignore_above_size");

                    b.Property<ushort>("MaxCompletionPercentage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_completion_percentage");

                    b.Property<int>("MaxStrikes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_strikes");

                    b.Property<double>("MaxTimeHours")
                        .HasColumnType("REAL")
                        .HasColumnName("max_time_hours");

                    b.Property<ushort>("MinCompletionPercentage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_completion_percentage");

                    b.Property<string>("MinSpeed")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("min_speed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PrivacyType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("privacy_type");

                    b.Property<Guid>("QueueCleanerConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("queue_cleaner_config_id");

                    b.Property<bool>("ResetStrikesOnProgress")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reset_strikes_on_progress");

                    b.HasKey("Id")
                        .HasName("pk_slow_rules");

                    b.HasIndex("QueueCleanerConfigId")
                        .HasDatabaseName("ix_slow_rules_queue_cleaner_config_id");

                    b.ToTable("slow_rules", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.QueueCleaner.StallRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("ChangeCategory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("change_category");

                    b.Property<bool>("DeletePrivateTorrentsFromClient")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delete_private_torrents_from_client");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<ushort>("MaxCompletionPercentage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_completion_percentage");

                    b.Property<int>("MaxStrikes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_strikes");

                    b.Property<ushort>("MinCompletionPercentage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_completion_percentage");

                    b.Property<string>("MinimumProgress")
                        .HasColumnType("TEXT")
                        .HasColumnName("minimum_progress");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PrivacyType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("privacy_type");

                    b.Property<Guid>("QueueCleanerConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("queue_cleaner_config_id");

                    b.Property<bool>("ResetStrikesOnProgress")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reset_strikes_on_progress");

                    b.HasKey("Id")
                        .HasName("pk_stall_rules");

                    b.HasIndex("QueueCleanerConfigId")
                        .HasDatabaseName("ix_stall_rules_queue_cleaner_config_id");

                    b.ToTable("stall_rules", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Seeker.SeekerConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("PostReleaseGraceHours")
                        .HasColumnType("INTEGER")
                        .HasColumnName("post_release_grace_hours");

                    b.Property<bool>("ProactiveSearchEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("proactive_search_enabled");

                    b.Property<bool>("SearchEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("search_enabled");

                    b.Property<ushort>("SearchInterval")
                        .HasColumnType("INTEGER")
                        .HasColumnName("search_interval");

                    b.Property<string>("SelectionStrategy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("selection_strategy");

                    b.Property<bool>("UseRoundRobin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("use_round_robin");

                    b.HasKey("Id")
                        .HasName("pk_seeker_configs");

                    b.ToTable("seeker_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Seeker.SeekerInstanceConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("ActiveDownloadLimit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active_download_limit");

                    b.Property<Guid>("ArrInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("arr_instance_id");

                    b.Property<Guid>("CurrentCycleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_cycle_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("LastProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_processed_at");

                    b.Property<int>("MinCycleTimeDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_cycle_time_days");

                    b.Property<bool>("MonitoredOnly")
                        .HasColumnType("INTEGER")
                        .HasColumnName("monitored_only");

                    b.PrimitiveCollection<string>("SkipTags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("skip_tags");

                    b.Property<int>("TotalEligibleItems")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_eligible_items");

                    b.Property<bool>("UseCustomFormatScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("use_custom_format_score");

                    b.Property<bool>("UseCutoff")
                        .HasColumnType("INTEGER")
                        .HasColumnName("use_cutoff");

                    b.HasKey("Id")
                        .HasName("pk_seeker_instance_configs");

                    b.HasIndex("ArrInstanceId")
                        .IsUnique()
                        .HasDatabaseName("ix_seeker_instance_configs_arr_instance_id");

                    b.ToTable("seeker_instance_configs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.BlacklistSyncHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("DownloadClientId")
                        .HasColumnType("TEXT")
                        .HasColumnName("download_client_id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.HasKey("Id")
                        .HasName("pk_blacklist_sync_history");

                    b.HasIndex("DownloadClientId")
                        .HasDatabaseName("ix_blacklist_sync_history_download_client_id");

                    b.HasIndex("Hash")
                        .HasDatabaseName("ix_blacklist_sync_history_hash");

                    b.HasIndex("Hash", "DownloadClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_blacklist_sync_history_hash_download_client_id");

                    b.ToTable("blacklist_sync_history", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.CustomFormatScoreEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ArrInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("arr_instance_id");

                    b.Property<int>("CurrentScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_score");

                    b.Property<int>("CutoffScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cutoff_score");

                    b.Property<long>("EpisodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.Property<long>("ExternalItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("external_item_id");

                    b.Property<long>("FileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_id");

                    b.Property<bool>("IsMonitored")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_monitored");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_type");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_synced_at");

                    b.Property<DateTimeOffset?>("LastUpgradedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_upgraded_at");

                    b.Property<string>("QualityProfileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("quality_profile_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_custom_format_score_entries");

                    b.HasIndex("LastUpgradedAt")
                        .HasDatabaseName("ix_custom_format_score_entries_last_upgraded_at");

                    b.HasIndex("ArrInstanceId", "ExternalItemId", "EpisodeId")
                        .IsUnique()
                        .HasDatabaseName("ix_custom_format_score_entries_arr_instance_id_external_item_id_episode_id");

                    b.ToTable("custom_format_score_entries", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.CustomFormatScoreHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ArrInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("arr_instance_id");

                    b.Property<int>("CutoffScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cutoff_score");

                    b.Property<long>("EpisodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.Property<long>("ExternalItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("external_item_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_type");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_custom_format_score_history");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("ix_custom_format_score_history_recorded_at");

                    b.HasIndex("ArrInstanceId", "ExternalItemId", "EpisodeId")
                        .HasDatabaseName("ix_custom_format_score_history_arr_instance_id_external_item_id_episode_id");

                    b.ToTable("custom_format_score_history", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.SearchQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ArrInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("arr_instance_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<string>("SearchType")
                        .HasColumnType("TEXT")
                        .HasColumnName("search_type");

                    b.Property<long?>("SeriesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("series_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_search_queue");

                    b.HasIndex("ArrInstanceId")
                        .HasDatabaseName("ix_search_queue_arr_instance_id");

                    b.ToTable("search_queue", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.SeekerCommandTracker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ArrInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("arr_instance_id");

                    b.Property<long>("CommandId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<long>("ExternalItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("external_item_id");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_title");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_seeker_command_trackers");

                    b.HasIndex("ArrInstanceId")
                        .HasDatabaseName("ix_seeker_command_trackers_arr_instance_id");

                    b.ToTable("seeker_command_trackers", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.SeekerHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ArrInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("arr_instance_id");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cycle_id");

                    b.Property<long>("ExternalItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("external_item_id");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_dry_run");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_title");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_type");

                    b.Property<DateTimeOffset>("LastSearchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_searched_at");

                    b.Property<int>("SearchCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("search_count");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_number");

                    b.HasKey("Id")
                        .HasName("pk_seeker_history");

                    b.HasIndex("ArrInstanceId", "ExternalItemId", "ItemType", "SeasonNumber", "CycleId")
                        .IsUnique()
                        .HasDatabaseName("ix_seeker_history_arr_instance_id_external_item_id_item_type_season_number_cycle_id");

                    b.ToTable("seeker_history", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Arr.ArrInstance", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.Arr.ArrConfig", "ArrConfig")
                        .WithMany("Instances")
                        .HasForeignKey("ArrConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_arr_instances_arr_configs_arr_config_id");

                    b.Navigation("ArrConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.DeadTorrentConfig", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.DownloadClientConfig", "DownloadClientConfig")
                        .WithMany()
                        .HasForeignKey("DownloadClientConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dead_torrent_configs_download_clients_download_client_config_id");

                    b.Navigation("DownloadClientConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.DelugeSeedingRule", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.DownloadClientConfig", "DownloadClientConfig")
                        .WithMany()
                        .HasForeignKey("DownloadClientConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deluge_seeding_rules_download_clients_download_client_config_id");

                    b.Navigation("DownloadClientConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.OrphanedFilesConfig", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.DownloadClientConfig", "DownloadClientConfig")
                        .WithMany()
                        .HasForeignKey("DownloadClientConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orphaned_files_configs_download_clients_download_client_config_id");

                    b.Navigation("DownloadClientConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.QBitSeedingRule", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.DownloadClientConfig", "DownloadClientConfig")
                        .WithMany()
                        .HasForeignKey("DownloadClientConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_q_bit_seeding_rules_download_clients_download_client_config_id");

                    b.Navigation("DownloadClientConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.RTorrentSeedingRule", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.DownloadClientConfig", "DownloadClientConfig")
                        .WithMany()
                        .HasForeignKey("DownloadClientConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_r_torrent_seeding_rules_download_clients_download_client_config_id");

                    b.Navigation("DownloadClientConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.TransmissionSeedingRule", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.DownloadClientConfig", "DownloadClientConfig")
                        .WithMany()
                        .HasForeignKey("DownloadClientConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transmission_seeding_rules_download_clients_download_client_config_id");

                    b.Navigation("DownloadClientConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.UTorrentSeedingRule", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.DownloadClientConfig", "DownloadClientConfig")
                        .WithMany()
                        .HasForeignKey("DownloadClientConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_u_torrent_seeding_rules_download_clients_download_client_config_id");

                    b.Navigation("DownloadClientConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.DownloadCleaner.UnlinkedConfig", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.DownloadClientConfig", "DownloadClientConfig")
                        .WithMany()
                        .HasForeignKey("DownloadClientConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unlinked_configs_download_clients_download_client_config_id");

                    b.Navigation("DownloadClientConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.AppriseConfig", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.Notification.NotificationConfig", "NotificationConfig")
                        .WithOne("AppriseConfiguration")
                        .HasForeignKey("Cleanuparr.Persistence.Models.Configuration.Notification.AppriseConfig", "NotificationConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_apprise_configs_notification_configs_notification_config_id");

                    b.Navigation("NotificationConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.DiscordConfig", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.Notification.NotificationConfig", "NotificationConfig")
                        .WithOne("DiscordConfiguration")
                        .HasForeignKey("Cleanuparr.Persistence.Models.Configuration.Notification.DiscordConfig", "NotificationConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discord_configs_notification_configs_notification_config_id");

                    b.Navigation("NotificationConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.GotifyConfig", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.Notification.NotificationConfig", "NotificationConfig")
                        .WithOne("GotifyConfiguration")
                        .HasForeignKey("Cleanuparr.Persistence.Models.Configuration.Notification.GotifyConfig", "NotificationConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gotify_configs_notification_configs_notification_config_id");

                    b.Navigation("NotificationConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.NotifiarrConfig", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.Notification.NotificationConfig", "NotificationConfig")
                        .WithOne("NotifiarrConfiguration")
                        .HasForeignKey("Cleanuparr.Persistence.Models.Configuration.Notification.NotifiarrConfig", "NotificationConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifiarr_configs_notification_configs_notification_config_id");

                    b.Navigation("NotificationConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.NtfyConfig", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.Notification.NotificationConfig", "NotificationConfig")
                        .WithOne("NtfyConfiguration")
                        .HasForeignKey("Cleanuparr.Persistence.Models.Configuration.Notification.NtfyConfig", "NotificationConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ntfy_configs_notification_configs_notification_config_id");

                    b.Navigation("NotificationConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.PushoverConfig", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.Notification.NotificationConfig", "NotificationConfig")
                        .WithOne("PushoverConfiguration")
                        .HasForeignKey("Cleanuparr.Persistence.Models.Configuration.Notification.PushoverConfig", "NotificationConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pushover_configs_notification_configs_notification_config_id");

                    b.Navigation("NotificationConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.TelegramConfig", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.Notification.NotificationConfig", "NotificationConfig")
                        .WithOne("TelegramConfiguration")
                        .HasForeignKey("Cleanuparr.Persistence.Models.Configuration.Notification.TelegramConfig", "NotificationConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_configs_notification_configs_notification_config_id");

                    b.Navigation("NotificationConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.QueueCleaner.SlowRule", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.QueueCleaner.QueueCleanerConfig", "QueueCleanerConfig")
                        .WithMany("SlowRules")
                        .HasForeignKey("QueueCleanerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_slow_rules_queue_cleaner_configs_queue_cleaner_config_id");

                    b.Navigation("QueueCleanerConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.QueueCleaner.StallRule", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.QueueCleaner.QueueCleanerConfig", "QueueCleanerConfig")
                        .WithMany("StallRules")
                        .HasForeignKey("QueueCleanerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stall_rules_queue_cleaner_configs_queue_cleaner_config_id");

                    b.Navigation("QueueCleanerConfig");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Seeker.SeekerInstanceConfig", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.Arr.ArrInstance", "ArrInstance")
                        .WithMany()
                        .HasForeignKey("ArrInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seeker_instance_configs_arr_instances_arr_instance_id");

                    b.Navigation("ArrInstance");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.BlacklistSyncHistory", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.DownloadClientConfig", "DownloadClient")
                        .WithMany()
                        .HasForeignKey("DownloadClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blacklist_sync_history_download_clients_download_client_id");

                    b.Navigation("DownloadClient");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.CustomFormatScoreEntry", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.Arr.ArrInstance", "ArrInstance")
                        .WithMany()
                        .HasForeignKey("ArrInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_format_score_entries_arr_instances_arr_instance_id");

                    b.Navigation("ArrInstance");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.CustomFormatScoreHistory", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.Arr.ArrInstance", "ArrInstance")
                        .WithMany()
                        .HasForeignKey("ArrInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_format_score_history_arr_instances_arr_instance_id");

                    b.Navigation("ArrInstance");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.SearchQueueItem", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.Arr.ArrInstance", "ArrInstance")
                        .WithMany()
                        .HasForeignKey("ArrInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_search_queue_arr_instances_arr_instance_id");

                    b.Navigation("ArrInstance");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.SeekerCommandTracker", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.Arr.ArrInstance", "ArrInstance")
                        .WithMany()
                        .HasForeignKey("ArrInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seeker_command_trackers_arr_instances_arr_instance_id");

                    b.Navigation("ArrInstance");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.SeekerHistory", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.Configuration.Arr.ArrInstance", "ArrInstance")
                        .WithMany()
                        .HasForeignKey("ArrInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seeker_history_arr_instances_arr_instance_id");

                    b.Navigation("ArrInstance");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Arr.ArrConfig", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.Notification.NotificationConfig", b =>
                {
                    b.Navigation("AppriseConfiguration");

                    b.Navigation("DiscordConfiguration");

                    b.Navigation("GotifyConfiguration");

                    b.Navigation("NotifiarrConfiguration");

                    b.Navigation("NtfyConfiguration");

                    b.Navigation("PushoverConfiguration");

                    b.Navigation("TelegramConfiguration");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Configuration.QueueCleaner.QueueCleanerConfig", b =>
                {
                    b.Navigation("SlowRules");

                    b.Navigation("StallRules");
                });
#pragma warning restore 612, 618
        }
    }
}
